version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python ./src/app.py"
    image: webapp:2.0
    ports:
      - 4100:4000
    # volumes:
    #   - .:/app
